### ISSUE TITLE
Play Store shows updates for a installed GitHub flavor of the app but fails with Could not update error

### ISSUE THREAD

**Issue by muznyo** [AChep/keyguard-app#117]
Keyguard is showing up in play store update page, but it cant be updated, because it's github version. Can it be hidden somehow?

![Screenshot_20240126_100543_Google Play Store](https://github.com/AChep/keyguard-app/assets/24987471/92d9b141-ebdb-48b0-af9c-d0360f2b4187)

**Comment by AChep** [comment]
The version on Play store has the same package name as the one on GitHub but has a different signature. This is what probably causing the could not update error.

The solution to that would be to make the GitHub version have a different package name. That probably makes sense but I want to check how the others are doing it first.

**Comment by NikunjKhangwal** [comment]
It's actually play store's fault. They recently decided to show updates for apps with different signing  keys. So even if you downloaded the app from somewhere else instead of play store it'll still show up. You can't update it because even though the app have same package name it's signed by a different person. One solution is using detach magisk module if you're rooted.

**Comment by AChep** [comment]
I've decided against maintaining a version with a different package name.
