### ISSUE TITLE
No Sync and no new items

### ISSUE THREAD

**Issue by ACDelta** [AChep/keyguard-app#331]
After purchasing the premium i added my account on the EU-Server. Login seems to work,  two faktor is also verified.
But after this, there is no sync. I can neither see existing records nor add new ("Cipher must have an account"), but there are no accounts selectable.

Unfortunately, since the app doesn't allow screenshots, I can't upload any here.

Please fix that problem!

**Comment by AChep** [comment]
If you go to Settings / Accounts / Your account, do you see your account or any sync errors in it? How many records does your account have?

PS: You can make screenshots if you check Settings / Security / Allow screenshots.

**Comment by ACDelta** [comment]
I see my account but no errors, even if i start sync manually.
![Unbenannt](https://github.com/AChep/keyguard-app/assets/36511056/8111c5cb-7ee1-4d95-bcfc-ebd3016207d1)

**Comment by ACDelta** [comment]
~1500 items, no folders and 1 organization.

**Comment by A3148475824** [comment]
Can I attempt self-troubleshooting by turning on an agent?
Or check it out by installing old installation packages!
Or log in with another device and see if you can try it!
Change the network!
Try using traffic
Problems can be accurately found through troubleshooting, so that developers can quickly fix them

**Comment by AChep** [comment]
Should be fixed now since https://github.com/AChep/keyguard-app/releases/tag/r20240620
