### ISSUE TITLE
[Windows enhancement] Require real-time protection

### ISSUE THREAD

**Issue by Cyber2525** [AChep/keyguard-app#515]
Require users to have the antivirus turned on to be able to decript the vault, otherwise it will display a popup saying that you need to turn on the realtime protection.

also if something is added on the antivirus exclusions that has the malware category of "remote acces" (ar anything that could steal tokens and passwords, the local vault will destroy automatically and login you out from bitwarden.

Idk if this only works in windows defender.

**Comment by AChep** [comment]
I don't like having to restrict people that have antivirus disabled but know what they are doing. There's no much benefit in auto-destroying the vault, because if the an antivirus has let a virus in for any amount of time you should consider all the sensitive data available from the machine as stolen. I might rethink this at some point in the future.
